#!/usr/bin/env python3
"""Deterministically select Paper-A points from a generated leakage map.

The selection is a constrained minimization, not a list of inherited
coordinates.  Each point covers a declared physical region of the
``(mu, chi)`` plane and is the lowest-leakage grid point in that region that
respects the declared separation from previously selected points.  Shared
anchors (P1, P2, P4, and L1) are stored once and reused by the corresponding
supplementary families.

The input must be the pure-code map generated by
``explore_resonance_mode_transition.py`` with ``epsilon=1e-3`` and
``phi_i(0)=0``.  The output JSON records the map hash, numerical protocol,
selection regions, distances, and selected leakage values.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Callable

import numpy as np


HERE = Path(__file__).resolve().parent
DEFAULT_MAP = HERE / "data" / "fig1_average_leakage.npz"
DEFAULT_MANIFEST = HERE / "data" / "selected_points_phi0.json"

EXPECTED_POLE_BIAS = 1.0e-3
EXPECTED_INITIAL_PHI = 0.0
EXPECTED_K = 100
EXPECTED_T_STOP = 9.96
EXPECTED_SAMPLE_COUNT = 250
EXPECTED_SOURCE = "generated_by_explore_resonance_mode_transition.py"

MAIN_MIN_DISTANCE = 0.12
VALLEY_MIN_DISTANCE = 0.05
ARC_MIN_DISTANCE = 0.08
RESONANCE_MIN_DISTANCE = 0.10
GLOBAL_MIN_DISTANCE = 0.05
ARC_MAX_LEAKAGE = 0.05
RESONANCE_MAX_LEAKAGE = 0.05


@dataclass(frozen=True)
class Region:
    point_id: str
    group: str
    mu_min: float
    mu_max: float
    chi_min: float
    chi_max: float
    max_leakage: float | None = None
    note: str = ""


@dataclass(frozen=True)
class Point:
    point_id: str
    group: str
    mu: float
    chi: float
    map_mean_leakage: float
    selection_note: str


# These windows encode parameter-space coverage, not old point coordinates.
# Their disjoint chi ranges keep P1--P6 representative of the weak-to-strong
# confinement comparison while the optimizer chooses the actual coordinates.
MAIN_REGIONS = (
    Region("P1", "main", -0.15, 0.10, 0.08, 0.20,
           note="first weak-confinement window"),
    Region("P2", "main", -0.15, 0.10, 0.22, 0.38,
           note="second weak-confinement window"),
    Region("P3", "main", -1.25, -0.62, 1.02, 1.22,
           ARC_MAX_LEAKAGE, "lower-left low-leakage window"),
    Region("P4", "main", -0.92, -0.45, 1.30, 1.48,
           ARC_MAX_LEAKAGE, "bottom window of the upper two-sided arc"),
    Region("P5", "main", -0.40, 0.08, 1.48, 1.68,
           ARC_MAX_LEAKAGE, "first strong-confinement window"),
    Region("P6", "main", -0.40, 0.08, 1.80, 1.95,
           ARC_MAX_LEAKAGE, "second strong-confinement window"),
)


VALLEY_REGIONS = (
    Region("V1", "valley", -0.15, 0.10, 0.06, 0.12,
           note="low-chi weak-confinement control"),
    # V2 is the shared P1 coordinate.
    Region("V3", "valley", -0.15, 0.10, 0.18, 0.26,
           note="intermediate weak-confinement control"),
    # V4 is the shared P2 coordinate.
    Region("V5", "valley", -0.15, 0.10, 0.36, 0.44,
           note="upper weak-confinement control"),
)


# Nine coverage windows trace the left arm, bottom, and right arm of the
# upper low-leakage structure.  A5 is exactly the data-selected P4 point.
UPPER_ARC_REGIONS = (
    Region("A1", "upper_arc", -1.42, -1.16, 1.78, 1.95,
           ARC_MAX_LEAKAGE, "upper-arc far left arm"),
    Region("A2", "upper_arc", -1.30, -1.02, 1.64, 1.82,
           ARC_MAX_LEAKAGE, "upper-arc left arm"),
    Region("A3", "upper_arc", -1.15, -0.86, 1.52, 1.68,
           ARC_MAX_LEAKAGE, "upper-arc inner left arm"),
    Region("A4", "upper_arc", -0.96, -0.69, 1.40, 1.55,
           ARC_MAX_LEAKAGE, "upper-arc near-bottom left arm"),
    Region("A6", "upper_arc", -0.68, -0.48, 1.40, 1.55,
           ARC_MAX_LEAKAGE, "upper-arc near-bottom right arm"),
    Region("A7", "upper_arc", -0.64, -0.38, 1.52, 1.68,
           ARC_MAX_LEAKAGE, "upper-arc inner right arm"),
    Region("A8", "upper_arc", -0.64, -0.36, 1.64, 1.82,
           ARC_MAX_LEAKAGE, "upper-arc right arm"),
    Region("A9", "upper_arc", -0.64, -0.34, 1.80, 1.95,
           ARC_MAX_LEAKAGE, "upper-arc far right arm"),
)


# L1 is selected directly on chi+2mu=0 and reused between this arc and the
# resonance-line row.  The remaining windows cover the two arms.
LOWER_ARC_REGIONS = (
    Region("B1", "lower_arc", -1.04, -0.78, 1.10, 1.24,
           ARC_MAX_LEAKAGE, "lower-arc far left arm"),
    Region("B2", "lower_arc", -0.88, -0.64, 1.00, 1.13,
           ARC_MAX_LEAKAGE, "lower-arc left arm"),
    Region("B3", "lower_arc", -0.68, -0.47, 0.88, 1.01,
           ARC_MAX_LEAKAGE, "lower-arc inner left arm"),
    Region("B5", "lower_arc", -0.33, -0.18, 0.70, 0.80,
           ARC_MAX_LEAKAGE, "lower-arc bottom"),
    Region("B6", "lower_arc", -0.23, -0.07, 0.78, 0.88,
           ARC_MAX_LEAKAGE, "lower-arc inner right arm"),
    Region("B7", "lower_arc", -0.23, -0.05, 0.88, 0.98,
           ARC_MAX_LEAKAGE, "lower-arc right arm"),
    Region("B8", "lower_arc", -0.21, -0.04, 1.00, 1.10,
           ARC_MAX_LEAKAGE, "lower-arc upper right arm"),
    Region("B9", "lower_arc", -0.21, -0.04, 1.12, 1.24,
           ARC_MAX_LEAKAGE, "lower-arc far right arm"),
)


RESONANCE_REGIONS = (
    Region("L1", "resonance_line", -0.50, -0.34, 0.78, 0.94,
           RESONANCE_MAX_LEAKAGE, "lowest-chi resonance anchor"),
    Region("L2", "resonance_line", -0.74, -0.58, 1.22, 1.44,
           RESONANCE_MAX_LEAKAGE, "second resonance window"),
    Region("L3", "resonance_line", -0.86, -0.72, 1.48, 1.68,
           RESONANCE_MAX_LEAKAGE, "third resonance window"),
    Region("L4", "resonance_line", -0.96, -0.82, 1.70, 1.86,
           RESONANCE_MAX_LEAKAGE, "fourth resonance window"),
    Region("L5", "resonance_line", -1.04, -0.92, 1.88, 2.00,
           RESONANCE_MAX_LEAKAGE, "highest-chi resonance window"),
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def scalar(archive: np.lib.npyio.NpzFile, key: str) -> Any:
    value = np.asarray(archive[key])
    if value.ndim != 0:
        raise ValueError(f"{key} must be scalar")
    return value.item()


def load_map(path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray, dict[str, Any]]:
    with np.load(path, allow_pickle=False) as archive:
        required = {
            "avg_q_leak", "mu", "chi", "pole_bias", "initial_phi", "K",
            "t_stop", "sample_count", "source_name", "protocol_key",
        }
        missing = sorted(required.difference(archive.files))
        if missing:
            raise ValueError(f"map lacks fields: {', '.join(missing)}")
        mu = np.asarray(archive["mu"], dtype=float)
        chi = np.asarray(archive["chi"], dtype=float)
        leakage = np.asarray(archive["avg_q_leak"], dtype=float)
        metadata = {
            "pole_bias": float(scalar(archive, "pole_bias")),
            "initial_phi": float(scalar(archive, "initial_phi")),
            "K": int(scalar(archive, "K")),
            "t_stop": float(scalar(archive, "t_stop")),
            "sample_count": int(scalar(archive, "sample_count")),
            "source_name": str(scalar(archive, "source_name")),
            "protocol_key": str(scalar(archive, "protocol_key")),
        }
    if leakage.shape != (mu.size, chi.size):
        raise ValueError("map arrays have inconsistent shapes")
    if not (np.all(np.isfinite(leakage)) and np.all(np.diff(mu) > 0)
            and np.all(np.diff(chi) > 0)):
        raise ValueError("map is nonfinite or unordered")
    expected = {
        "pole_bias": EXPECTED_POLE_BIAS,
        "initial_phi": EXPECTED_INITIAL_PHI,
        "K": EXPECTED_K,
        "t_stop": EXPECTED_T_STOP,
        "sample_count": EXPECTED_SAMPLE_COUNT,
        "source_name": EXPECTED_SOURCE,
    }
    for key, value in expected.items():
        actual = metadata[key]
        if isinstance(value, float):
            if not np.isclose(actual, value, rtol=0.0, atol=1.0e-14):
                raise ValueError(f"map {key}={actual!r}, expected {value!r}")
        elif actual != value:
            raise ValueError(f"map {key}={actual!r}, expected {value!r}")
    return mu, chi, leakage, metadata


def distance(first: Point, second: Point) -> float:
    return float(np.hypot(first.mu - second.mu, first.chi - second.chi))


def region_candidates(
    region: Region,
    mu: np.ndarray,
    chi: np.ndarray,
    leakage: np.ndarray,
    predicate: Callable[[float, float], bool] | None = None,
) -> list[Point]:
    """Return the region's grid points ordered by leakage, then coordinates."""

    mu_indices = np.where((mu >= region.mu_min) & (mu <= region.mu_max))[0]
    chi_indices = np.where((chi >= region.chi_min) & (chi <= region.chi_max))[0]
    candidates: list[Point] = []
    for mu_index in mu_indices:
        for chi_index in chi_indices:
            mu_value = float(mu[mu_index])
            chi_value = float(chi[chi_index])
            if predicate is not None and not predicate(mu_value, chi_value):
                continue
            leakage_value = float(leakage[mu_index, chi_index])
            if (
                region.max_leakage is not None
                and leakage_value >= region.max_leakage
            ):
                continue
            candidates.append(
                Point(
                    region.point_id,
                    region.group,
                    mu_value,
                    chi_value,
                    leakage_value,
                    "",
                )
            )
    candidates.sort(
        key=lambda point: (point.map_mean_leakage, point.chi, point.mu)
    )
    return candidates


def _spacing_constraints(
    occupied: list[Point],
    family_points: list[Point],
    family_minimum_distance: float,
    anchors: tuple[Point, ...] = (),
) -> list[tuple[Point, float]]:
    """Combine global spacing with stronger within-family constraints."""

    constraints: dict[tuple[float, float], tuple[Point, float]] = {
        (point.mu, point.chi): (point, GLOBAL_MIN_DISTANCE)
        for point in occupied
    }
    for point in [*family_points, *anchors]:
        key = (point.mu, point.chi)
        previous = constraints.get(key)
        required = max(
            family_minimum_distance,
            previous[1] if previous is not None else 0.0,
        )
        constraints[key] = (point, required)
    return list(constraints.values())


def _admissible(
    candidate: Point, constraints: list[tuple[Point, float]]
) -> bool:
    return all(
        distance(candidate, point) >= required - 1.0e-12
        for point, required in constraints
    )


def choose_region(
    region: Region,
    mu: np.ndarray,
    chi: np.ndarray,
    leakage: np.ndarray,
    constraints: list[tuple[Point, float]],
    selection_rule: str,
    predicate: Callable[[float, float], bool] | None = None,
) -> Point:
    """Choose the lowest-leakage admissible grid point in one region."""

    for candidate in region_candidates(region, mu, chi, leakage, predicate):
        if _admissible(candidate, constraints):
            return Point(
                **{
                    **asdict(candidate),
                    "selection_note": (
                        f"minimum map leakage in "
                        f"mu=[{region.mu_min},{region.mu_max}], "
                        f"chi=[{region.chi_min},{region.chi_max}] under "
                        f"{selection_rule}; {region.note}"
                    ),
                }
            )
    raise ValueError(
        f"no admissible candidate for {region.point_id} in its declared region"
    )


def choose_weak_pair(
    mu: np.ndarray,
    chi: np.ndarray,
    leakage: np.ndarray,
) -> tuple[Point, Point]:
    """Jointly minimize the P1/P2 leakage sum at fixed main-point spacing."""

    first_region, second_region = MAIN_REGIONS[:2]
    first_candidates = region_candidates(first_region, mu, chi, leakage)
    second_candidates = region_candidates(second_region, mu, chi, leakage)
    admissible_pairs = (
        (first, second)
        for first in first_candidates
        for second in second_candidates
        if distance(first, second) >= MAIN_MIN_DISTANCE - 1.0e-12
    )
    try:
        first, second = min(
            admissible_pairs,
            key=lambda pair: (
                pair[0].map_mean_leakage + pair[1].map_mean_leakage,
                max(pair[0].map_mean_leakage, pair[1].map_mean_leakage),
                pair[0].map_mean_leakage,
                pair[0].chi,
                pair[1].chi,
                pair[0].mu,
                pair[1].mu,
            ),
        )
    except ValueError as exc:
        raise ValueError("no admissible P1/P2 pair") from exc
    rule = (
        f"joint minimum of the P1+P2 map leakage with pair distance"
        f">={MAIN_MIN_DISTANCE}"
    )
    return tuple(
        Point(
            **{
                **asdict(point),
                "selection_note": (
                    f"{rule}; mu=[{region.mu_min},{region.mu_max}], "
                    f"chi=[{region.chi_min},{region.chi_max}]; {region.note}"
                ),
            }
        )
        for point, region in zip(
            (first, second), (first_region, second_region), strict=True
        )
    )


def select_all(mu: np.ndarray, chi: np.ndarray, leakage: np.ndarray) -> dict[str, list[Point]]:
    occupied: list[Point] = []
    main = list(choose_weak_pair(mu, chi, leakage))
    occupied.extend(main)
    for region in MAIN_REGIONS[2:]:
        point = choose_region(
            region,
            mu,
            chi,
            leakage,
            _spacing_constraints(
                occupied, main, MAIN_MIN_DISTANCE
            ),
            f"all P1--P6 distances>={MAIN_MIN_DISTANCE}",
        )
        main.append(point)
        occupied.append(point)
    main_by_id = {point.point_id: point for point in main}

    valley: list[Point] = []
    point = choose_region(
        VALLEY_REGIONS[0],
        mu,
        chi,
        leakage,
        _spacing_constraints(
            occupied,
            valley,
            VALLEY_MIN_DISTANCE,
            (main_by_id["P1"], main_by_id["P2"]),
        ),
        (
            f"valley distances>={VALLEY_MIN_DISTANCE} and all other "
            f"distinct-point distances>={GLOBAL_MIN_DISTANCE}"
        ),
    )
    valley.append(point)
    occupied.append(point)
    valley.append(
        Point(**{**asdict(main_by_id["P1"]), "point_id": "V2", "group": "valley",
                 "selection_note": "shared data-selected P1 anchor"})
    )
    point = choose_region(
        VALLEY_REGIONS[1],
        mu,
        chi,
        leakage,
        _spacing_constraints(
            occupied,
            valley,
            VALLEY_MIN_DISTANCE,
            (main_by_id["P1"], main_by_id["P2"]),
        ),
        (
            f"valley distances>={VALLEY_MIN_DISTANCE} and all other "
            f"distinct-point distances>={GLOBAL_MIN_DISTANCE}"
        ),
    )
    valley.append(point)
    occupied.append(point)
    valley.append(
        Point(**{**asdict(main_by_id["P2"]), "point_id": "V4", "group": "valley",
                 "selection_note": "shared data-selected P2 anchor"})
    )
    point = choose_region(
        VALLEY_REGIONS[2],
        mu,
        chi,
        leakage,
        _spacing_constraints(
            occupied,
            valley,
            VALLEY_MIN_DISTANCE,
            (main_by_id["P1"], main_by_id["P2"]),
        ),
        (
            f"valley distances>={VALLEY_MIN_DISTANCE} and all other "
            f"distinct-point distances>={GLOBAL_MIN_DISTANCE}"
        ),
    )
    valley.append(point)
    occupied.append(point)

    upper_arc: list[Point] = []
    for region in UPPER_ARC_REGIONS[:4]:
        point = choose_region(
            region,
            mu,
            chi,
            leakage,
            _spacing_constraints(
                occupied,
                upper_arc,
                ARC_MIN_DISTANCE,
                (main_by_id["P4"],),
            ),
            (
                f"within-arc distances>={ARC_MIN_DISTANCE} and all other "
                f"distinct-point distances>={GLOBAL_MIN_DISTANCE}"
            ),
        )
        upper_arc.append(point)
        occupied.append(point)
    upper_arc.append(
        Point(**{**asdict(main_by_id["P4"]), "point_id": "A5", "group": "upper_arc",
                 "selection_note": "shared data-selected P4 anchor"})
    )
    for region in UPPER_ARC_REGIONS[4:]:
        point = choose_region(
            region,
            mu,
            chi,
            leakage,
            _spacing_constraints(
                occupied,
                upper_arc,
                ARC_MIN_DISTANCE,
                (main_by_id["P4"],),
            ),
            (
                f"within-arc distances>={ARC_MIN_DISTANCE} and all other "
                f"distinct-point distances>={GLOBAL_MIN_DISTANCE}"
            ),
        )
        upper_arc.append(point)
        occupied.append(point)

    resonance: list[Point] = []
    resonance_predicate = lambda mu_value, chi_value: abs(
        chi_value + 2.0 * mu_value
    ) <= 5.1e-3
    for region in RESONANCE_REGIONS:
        point = choose_region(
            region,
            mu,
            chi,
            leakage,
            _spacing_constraints(
                occupied, resonance, RESONANCE_MIN_DISTANCE
            ),
            (
                f"resonance-line distances>={RESONANCE_MIN_DISTANCE} and "
                f"all other distinct-point distances>={GLOBAL_MIN_DISTANCE}"
            ),
            predicate=resonance_predicate,
        )
        resonance.append(point)
        occupied.append(point)
    resonance_by_id = {point.point_id: point for point in resonance}

    lower_arc: list[Point] = []
    for region in LOWER_ARC_REGIONS[:3]:
        point = choose_region(
            region,
            mu,
            chi,
            leakage,
            _spacing_constraints(
                occupied,
                lower_arc,
                ARC_MIN_DISTANCE,
                (resonance_by_id["L1"],),
            ),
            (
                f"within-arc distances>={ARC_MIN_DISTANCE} and all other "
                f"distinct-point distances>={GLOBAL_MIN_DISTANCE}"
            ),
        )
        lower_arc.append(point)
        occupied.append(point)
    lower_arc.append(
        Point(**{**asdict(resonance_by_id["L1"]), "point_id": "L1", "group": "lower_arc",
                 "selection_note": "shared data-selected resonance anchor"})
    )
    for region in LOWER_ARC_REGIONS[3:]:
        point = choose_region(
            region,
            mu,
            chi,
            leakage,
            _spacing_constraints(
                occupied,
                lower_arc,
                ARC_MIN_DISTANCE,
                (resonance_by_id["L1"],),
            ),
            (
                f"within-arc distances>={ARC_MIN_DISTANCE} and all other "
                f"distinct-point distances>={GLOBAL_MIN_DISTANCE}"
            ),
        )
        lower_arc.append(point)
        occupied.append(point)

    families = {
        "main": main,
        "valley": valley,
        "upper_arc": upper_arc,
        "lower_arc": lower_arc,
        "resonance_line": resonance,
    }
    for name, points in families.items():
        unique = {(point.mu, point.chi) for point in points}
        if len(unique) != len(points):
            raise AssertionError(f"duplicate coordinates inside {name}")
        distances = [
            distance(first, second)
            for index, first in enumerate(points)
            for second in points[index + 1 :]
        ]
        required = {
            "main": MAIN_MIN_DISTANCE,
            "valley": VALLEY_MIN_DISTANCE,
            "upper_arc": ARC_MIN_DISTANCE,
            "lower_arc": ARC_MIN_DISTANCE,
            "resonance_line": RESONANCE_MIN_DISTANCE,
        }[name]
        if distances and min(distances) < required - 1.0e-12:
            raise ValueError(
                f"{name} minimum spacing {min(distances):.6f} < {required}"
            )
    return families


def regions_as_dict() -> dict[str, list[dict[str, Any]]]:
    return {
        "main": [asdict(region) for region in MAIN_REGIONS],
        "valley_nonshared": [asdict(region) for region in VALLEY_REGIONS],
        "upper_arc_nonshared": [asdict(region) for region in UPPER_ARC_REGIONS],
        "lower_arc_nonshared": [asdict(region) for region in LOWER_ARC_REGIONS],
        "resonance_line": [asdict(region) for region in RESONANCE_REGIONS],
    }


def write_manifest(map_path: Path, output_path: Path) -> dict[str, Any]:
    mu, chi, leakage, metadata = load_map(map_path)
    families = select_all(mu, chi, leakage)
    manifest = {
        "schema_version": 1,
        "map_path": str(map_path.resolve()),
        "map_sha256": sha256(map_path),
        "map_shape": list(leakage.shape),
        "map_protocol": metadata,
        "constraints": {
            "main_min_distance": MAIN_MIN_DISTANCE,
            "valley_min_distance": VALLEY_MIN_DISTANCE,
            "arc_min_distance": ARC_MIN_DISTANCE,
            "resonance_min_distance": RESONANCE_MIN_DISTANCE,
            "global_min_distance": GLOBAL_MIN_DISTANCE,
            "upper_and_lower_arc_max_leakage": ARC_MAX_LEAKAGE,
            "resonance_max_leakage": RESONANCE_MAX_LEAKAGE,
            "objective": (
                "jointly minimize the P1+P2 map leakage; for every other "
                "point, minimize map leakage in its declared coverage region "
                "subject to the recorded spacing constraints"
            ),
            "regions": regions_as_dict(),
        },
        "shared_anchors": {
            "V2": "P1",
            "V4": "P2",
            "A5": "P4",
            "lower_arc_L1": "resonance_line_L1",
        },
        "families": {
            name: [asdict(point) for point in points]
            for name, points in families.items()
        },
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--map", type=Path, default=DEFAULT_MAP)
    parser.add_argument("--output", type=Path, default=DEFAULT_MANIFEST)
    args = parser.parse_args()
    manifest = write_manifest(args.map.resolve(), args.output.resolve())
    print(json.dumps({
        "status": "ok",
        "manifest": str(args.output.resolve()),
        "map_sha256": manifest["map_sha256"],
        "main_points": manifest["families"]["main"],
    }, indent=2))


if __name__ == "__main__":
    main()
